kind: pipeline
name: default

environment:
  APP_VER: 3.4.10
  APP_VER_BUILD: ${DRONE_BUILD_NUMBER}
  APP_BUILD_COMMIT: ${DRONE_COMMIT_SHA:0:7}
  APP_BUILD_DATE: ${DRONE_BUILD_FINISHED}

trigger:
  event:
  - push
  branch:
  - master

platform:
  os: linux
  arch: amd64

volumes:
  - name: docker
    host:
      path: /var/cache/drone/${DRONE_REPO}/${DRONE_STAGE_NAME}

steps:
- name: build&publish
  image: plugins/docker
  settings:
    repo: izdock/postfix
    build_args_from_env:
    - APP_VER
    - APP_VER_BUILD
    - APP_BUILD_COMMIT
    - APP_BUILD_DATE
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    tags:
      - latest
      - ${DRONE_TAG}
      - ${DRONE_TAG%.*}
      - ${DRONE_TAG%%.*}
      - ${DRONE_TAG}-${DRONE_BUILD_NUMBER}
      - ${DRONE_COMMIT_SHA:0:7}
  volumes:
  - name: docker
    path: /var/lib/docker
